services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./images:/static/images:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rabbits

  backend:
    image: eclipse-temurin:17.0.11_9-jdk-jammy
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      - SPRING_CONFIG_LOCATION=/app/application.properties
    volumes:
      - ./backend/build/battlepeople.jar:/app/app.jar:ro
      - ./backend/application.properties:/app/application.properties
      - ./images:/static/images:rw
    env_file:
      - backend/.env
    working_dir: /app
    networks:
      - rabbits
    entrypoint: ["sh", "-c", "java -jar $(ls *.jar | head -n 1)"]

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: VhGjVihJtfVUzhsT7m8y
      MYSQL_DATABASE: battlepeople
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data.sql:/docker-entrypoint-initdb.d/initdata.sql
    networks:
      - rabbits

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - rabbits

  openvidu:
    image: openvidu/openvidu-dev:2.30.0
    container_name: openvidu
    restart: always
    env_file:
      - .env.openvidu
    ports:
      - "4443:4443"
    networks:
      - rabbits

networks:
  rabbits:
    driver: bridge

volumes:
  mysql_data:
