version: '3.1'

services:
  openvidu-server:
    image: openvidu/openvidu-server-kms:latest
    environment:
      - OPENVIDU_SECRET=woowahanrabbits
      - OPENVIDU_PUBLICURL=https://localhost
    ports:
      - "4443:4443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  coturn:
    image: instrumentisto/coturn
    environment:
      - TZ=UTC
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    command: ["-n", "--log-file=stdout", "--min-port=49152", "--max-port=65535", "--lt-cred-mech", "--realm=localhost", "--user=myuser:kevinhomealone"]

  nginx:
    image: nginx:latest
    volumes:
      - C:/Users/SSAFY/Desktop/S11P12A706/battle-people-server/nginx.conf:/etc/nginx/nginx.conf
      - C:/Users/SSAFY/Desktop/S11P12A706/battle-people-server/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
      - C:/Users/SSAFY/Desktop/S11P12A706/battle-people-server/ssl/private.key:/etc/nginx/ssl/private.key
    ports:
      - "80:80"
      - "443:443"
